// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MindCare - Seu Assistente de Bem-Estar Mental",
  description: "Aplicativo de apoio ao bem-estar mental com chat terapêutico, rastreamento de humor, exercícios de mindfulness e acompanhamento de progresso. Ferramenta de apoio que não substitui profissionais de saúde mental.",
  keywords: ["bem-estar mental", "saúde mental", "mindfulness", "meditação", "ansiedade", "estresse", "humor"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}